-- Esegui questo script UNA VOLTA nel SQL Editor di Supabase.

create table if not exists public.packing_items (
  id bigint generated by default as identity primary key,
  category text not null,
  label text not null,
  checked boolean not null default false,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.packing_items enable row level security;

grant select, insert, update, delete on public.packing_items to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "Public read packing items" on public.packing_items;
drop policy if exists "Public insert packing items" on public.packing_items;
drop policy if exists "Public update packing items" on public.packing_items;
drop policy if exists "Public delete packing items" on public.packing_items;

create policy "Public read packing items"
on public.packing_items for select
to anon
using (true);

create policy "Public insert packing items"
on public.packing_items for insert
to anon
with check (true);

create policy "Public update packing items"
on public.packing_items for update
to anon
using (true)
with check (true);

create policy "Public delete packing items"
on public.packing_items for delete
to anon
using (true);

-- Abilita gli aggiornamenti realtime sulla tabella.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'packing_items'
  ) then
    alter publication supabase_realtime add table public.packing_items;
  end if;
end
$$;
